# Generated by Django 6.0.5 on 2026-05-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.IntegerField(primary_key=True, serialize=False)),
                ('position_name_fa', models.TextField()),
                ('position_name_eng', models.TextField()),
                ('position_can_login', models.BooleanField(default=False)),
                ('position_can_see_own_unit', models.BooleanField(default=False)),
                ('position_can_see_all_staff', models.BooleanField(default=False)),
                ('position_is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='shift',
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
