# Generated by Django 6.0.5 on 2026-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_position_remove_timetable_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_name_fa', models.TextField(blank=True, null=True)),
                ('contract_name_eng', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('month_id', models.AutoField(primary_key=True, serialize=False)),
                ('month_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('performance_id', models.AutoField(primary_key=True, serialize=False)),
                ('performance_working_days', models.IntegerField(blank=True, null=True)),
                ('performance_hourly_overtime', models.TextField(blank=True, null=True)),
                ('performance_hourly_leave', models.TextField(blank=True, null=True)),
                ('performance_hourly_absence', models.TextField(blank=True, null=True)),
                ('performance_daily_absence', models.IntegerField(blank=True, null=True)),
                ('performance_annual_leave', models.IntegerField(blank=True, null=True)),
                ('performance_sick_leave', models.IntegerField(blank=True, null=True)),
                ('performance_daily_reward_leave', models.IntegerField(blank=True, null=True)),
                ('performance_daily_mission', models.IntegerField(blank=True, null=True)),
                ('performance_proposed_overtime', models.IntegerField(blank=True, null=True)),
                ('performance_proposed_compensatory_timeoff', models.IntegerField(blank=True, null=True)),
                ('performance_approved_hourly_leave', models.TextField(blank=True, null=True)),
                ('performance_approved_overtime', models.IntegerField(blank=True, null=True)),
                ('performance_approved_compensatory_timeoff', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'performance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name_fa', models.TextField(blank=True, null=True)),
                ('staff_family_fa', models.TextField(blank=True, null=True)),
                ('staff_name_eng', models.TextField(blank=True, null=True)),
                ('staff_family_eng', models.TextField(blank=True, null=True)),
                ('staff_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name_fa', models.TextField(blank=True, null=True)),
                ('status_name_eng', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name_fa', models.TextField(blank=True, null=True)),
                ('unit_name_eng', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'year',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'managed': False},
        ),
    ]
